-- Preserve the eight ideas selected in the original dashboard workflow.
INSERT OR IGNORE INTO ideas
  (id, source_briefing_id, kind, related_project, title, summary, why_now,
   smallest_version, status, destination, pinned, tags_json, handoff_prompt,
   created_at, updated_at)
VALUES
  ('16a00000-0000-4000-8000-000000000001', NULL, 'new_project', '',
   'Auto-Updating Work Brain',
   'A personal work brain that keeps its own knowledge current as projects, decisions, and source material change.',
   'Saved from the original Project Vote on August 16, 2026.',
   'Recover and refine the original concept before choosing an implementation path.',
   'kept', 'undecided', 0, '["MONEY","PORTFOLIO","HELPS"]',
   'Prepare this idea for architecture review: Auto-Updating Work Brain.\n\nRecover and refine the original project concept, define the smallest useful version, and preserve the decisions already made in the dashboard project.',
   '2026-08-16T13:00:00.000Z', '2026-08-16T13:00:00.000Z'),

  ('16a00000-0000-4000-8000-000000000002', NULL, 'new_project', '',
   'Real-Time News-to-Action Pipeline',
   'Turn important live news signals into specific, useful actions instead of another stream of headlines.',
   'Saved from the original Project Vote on August 16, 2026.',
   'Recover and refine the original concept before choosing an implementation path.',
   'kept', 'undecided', 0, '["MONEY","PORTFOLIO","ADVENTURE"]',
   'Prepare this idea for architecture review: Real-Time News-to-Action Pipeline.\n\nRecover and refine the original project concept, define the smallest useful version, and preserve the decisions already made in the dashboard project.',
   '2026-08-16T13:01:00.000Z', '2026-08-16T13:01:00.000Z'),

  ('16a00000-0000-4000-8000-000000000003', NULL, 'new_project', '',
   'Speed-Optimized Workflow Analyzer',
   'Build a tool that measures and benchmarks actual AI response times across providers and models, then recommends faster alternatives for repeated tasks.',
   'The speed gap between models is changing quickly, so yesterday''s acceptable workflow may already be leaving time on the table.',
   'Log response times for three common AI tasks, compare providers, and flag any consistent performance difference greater than 20 percent.',
   'kept', 'undecided', 0, '["MONEY","PORTFOLIO","FUN"]',
   'Prepare this idea for architecture review: Speed-Optimized Workflow Analyzer.\n\nConcept: Measure real AI response times across providers and recommend faster alternatives.\n\nSmallest useful version: Log three common tasks and flag consistent performance differences above 20 percent.',
   '2026-08-16T13:02:00.000Z', '2026-08-16T13:02:00.000Z'),

  ('16a00000-0000-4000-8000-000000000004', NULL, 'new_project', '',
   'Rapid-Fire Research Digest Engine',
   'Build a continuously updated knowledge base that turns trending AI and technology headlines into structured, actionable briefing cards.',
   'Fast-moving technology news needs a system that keeps pace automatically instead of depending on manual curation.',
   'Pull five technology headlines on a schedule, extract why each matters and what it could unlock, store the results, and show them in a searchable table.',
   'kept', 'undecided', 0, '["PORTFOLIO","ADVENTURE","HELPS"]',
   'Prepare this idea for architecture review: Rapid-Fire Research Digest Engine.\n\nConcept: Convert live AI and technology headlines into structured, actionable briefing cards.\n\nSmallest useful version: Process five scheduled headlines and display the extracted insights in a searchable table.',
   '2026-08-16T13:03:00.000Z', '2026-08-16T13:03:00.000Z'),

  ('17a00000-0000-4000-8000-000000000005', NULL, 'new_project', '',
   'Policy Pitch Validator',
   'Stress-test policy ideas against real-world implementation scenarios using a structured debate among multiple AI perspectives.',
   'Independent AI policy work creates demand for tools that help people refine ideas before submission or public presentation.',
   'Accept one policy idea and generate an implementation officer, skeptic, and economist analysis that can become a shareable presentation.',
   'kept', 'undecided', 0, '["PORTFOLIO","HELPS","ADVENTURE"]',
   'Prepare this idea for architecture review: Policy Pitch Validator.\n\nConcept: Stress-test policy ideas through three structured AI perspectives.\n\nSmallest useful version: Analyze one pasted proposal as an implementation officer, skeptic, and economist, then prepare the output for presentation.',
   '2026-08-17T13:00:00.000Z', '2026-08-17T13:00:00.000Z'),

  ('17a00000-0000-4000-8000-000000000006', NULL, 'new_project', '',
   'Policy Idea Validator',
   'Stress-test policy proposals against economic opportunity and societal resilience, surfacing blind spots and unintended consequences.',
   'A rigorous, repeatable vetting method could demonstrate how complex ideas can be evaluated at scale.',
   'Accept policy text, assess job impact, equity distribution, and failure modes, then return a scored report with specific concerns.',
   'kept', 'undecided', 0, '["PORTFOLIO","HELPS","PROTECTS"]',
   'Prepare this idea for architecture review: Policy Idea Validator.\n\nConcept: Surface blind spots and unintended consequences in policy proposals.\n\nSmallest useful version: Score one proposal for job impact, equity distribution, and failure modes.',
   '2026-08-17T13:01:00.000Z', '2026-08-17T13:01:00.000Z'),

  ('18a00000-0000-4000-8000-000000000007', NULL, 'new_project', '',
   'Teen AI Voice Coach',
   'Let teens record themselves discussing a topic and receive coaching on clarity, critical thinking, fact-checking, and responsible AI framing.',
   'Teen-focused AI learning creates a timely opening for tools that teach evaluation and reasoning rather than passive AI use.',
   'Accept a pasted transcript or short audio clip and return coaching on clarity, verification needs, and argument quality without grading the student.',
   'kept', 'undecided', 0, '["HELPS","PORTFOLIO","ADVENTURE"]',
   'Prepare this idea for architecture review: Teen AI Voice Coach.\n\nConcept: Coach teens on clarity and critical thinking from a short voice recording.\n\nSmallest useful version: Transcribe one clip and provide supportive feedback across clarity, verification, and argument quality.',
   '2026-08-18T13:00:00.000Z', '2026-08-18T13:00:00.000Z'),

  ('18a00000-0000-4000-8000-000000000008', NULL, 'new_project', '',
   'Teen AI Voice Tutor',
   'Build an interactive voice tutor that teaches teens AI literacy through guided conversation and real-time feedback.',
   'Demand is growing for age-appropriate AI education with strong guardrails and an intentional learning structure.',
   'Accept teen voice input, transcribe it, ask useful clarifying questions, return spoken feedback, and retain enough history to show learning progress.',
   'kept', 'undecided', 0, '["HELPS","PORTFOLIO","PROTECTS"]',
   'Prepare this idea for architecture review: Teen AI Voice Tutor.\n\nConcept: Teach AI literacy through guided voice conversation.\n\nSmallest useful version: Accept one voice input, ask a clarifying question, return spoken feedback, and save the learning thread.',
   '2026-08-18T13:01:00.000Z', '2026-08-18T13:01:00.000Z');
